### ISSUE TITLE
[Bug]: branch bugfix/solidity_install failure in rebuild container 

### ISSUE THREAD

**Issue by matthiaszimmermann** [etherisc/gif-sandbox#9]
### What happened?

error message during rebuild container

[607659 ms] 
[607661 ms] 
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes[903297 ms] Container server: Remote to local stream terminated with error: {
  message: 'connect ENOENT \\\\.\\pipe\\openssh-ssh-agent',
  name: 'Error',
  stack: 'Error: connect ENOENT \\\\.\\pipe\\openssh-ssh-agent\n' +
    '\tat PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)'
}

Warning: Permanently added 'github.com,140.82.121.3' (ECDSA) to the list of known hosts.
Connection reset by 140.82.121.3 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: not a git repository (or any of the parent directories): .git
>>>> Compiling GIF contracts...
Brownie v1.19.3 - Python development framework for Ethereum

ERROR: Brownie environment has not been initiated for this folder.
Type 'brownie init' to create the file structure.
Deploying GIF contracts to ganache ...
Brownie v1.19.3 - Python development framework for Ethereum

No project was loaded.
Warning: Input is not a terminal (fd=0).
Brownie environment is ready.
>>> from scripts.instance import GifInstance
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'scripts'
>>> instance = GifInstance(accounts[0], accounts[1])
  File "<console>", line 1, in <module>
NameError: name 'GifInstance' is not defined
>>> f = open("/workspace/gif_instance_address.txt", "w")
>>> f.writelines("registry=%s\n" % (instance.getRegistry().address))
  File "<console>", line 1, in <module>
NameError: name 'instance' is not defined
>>> f.close()
>>>

>>>> GIF deployme

### What operating system are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Firefox

### What wallet extension are you using?

Metamask

### Rules

- [X] I agree to follow this project's rules

**Comment by Fenum88** [comment]
599813 ms] [15:56:00] Extracted extension to /home/vscode/.vscode-server/extensions/.04af128a-b941-4f4d-9c3a-d36c2e19509a: juanblanco.solidity
[599848 ms] [15:56:01] Renamed to /home/vscode/.vscode-server/extensions/juanblanco.solidity-0.0.141
[599855 ms] [15:56:01] Extracting completed. juanblanco.solidity
[599873 ms] [15:56:01] Extension installed successfully: juanblanco.solidity
[599876 ms] Extension 'juanblanco.solidity' v0.0.141 was successfully installed.
[607628 ms] Start: Run in container: mkdir -p '/vscode/vscode-server/extensionsCache' && cd '/home/vscode/.vscode-server/extensionsCache' && cp 'ms-python.isort-2022.8.0' 'ms-python.isort-2022.8.0.sigzip' 'tintinweb.solidity-visual-auditor-0.1.5' 'tintinweb.solidity-visual-auditor-0.1.5.sigzip' '/vscode/vscode-server/extensionsCache'
[607645 ms] 
[607646 ms] 
[607647 ms] Start: Run in container: cd '/vscode/vscode-server/extensionsCache' && ls -t | tail -n +50 | xargs rm -f
[607659 ms] 
[607661 ms] 
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes[903297 ms] Container server: Remote to local stream terminated with error: {
  message: 'connect ENOENT \\\\.\\pipe\\openssh-ssh-agent',
  name: 'Error',
  stack: 'Error: connect ENOENT \\\\.\\pipe\\openssh-ssh-agent\n' +
    '\tat PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)'
}

Warning: Permanently added 'github.com,140.82.121.3' (ECDSA) to the list of known hosts.
Connection reset by 140.82.121.3 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: not a git repository (or any of the parent directories): .git
>>>> Compiling GIF contracts...
Brownie v1.19.3 - Python development framework for Ethereum

ERROR: Brownie environment has not been initiated for this folder.
Type 'brownie init' to create the file structure.
Deploying GIF contracts to ganache ...
Brownie v1.19.3 - Python development framework for Ethereum

No project was loaded.
Warning: Input is not a terminal (fd=0).
Brownie environment is ready.
>>> from scripts.instance import GifInstance
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'scripts'
>>> instance = GifInstance(accounts[0], accounts[1])
  File "<console>", line 1, in <module>
NameError: name 'GifInstance' is not defined
>>> f = open("/workspace/gif_instance_address.txt", "w")
>>> f.writelines("registry=%s\n" % (instance.getRegistry().address))
  File "<console>", line 1, in <module>
NameError: name 'instance' is not defined
>>> f.close()
>>>

>>>> GIF deployment completed. Registry address is saved in gif_instance_address.txt
[912748 ms] Start: Run in container: # Test for /home/vscode/.gitconfig and git
[912763 ms] 
[912764

**Comment by Fenum88** [comment]
VSC:
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Docker 20.10.22
Windows 10 Pro
GPU:  INTEL(R) UHD Graphics 605

**Comment by doerfli** [comment]
@Fenum88 can you please retry creating the dev container using the `master` branch. thanks.

**Comment by Fenum88** [comment]
Sorry still not working same error then bevor

+] Building 2.4s (3/3) FINISHED
 => [internal] load build definition from Dockerfile.ganache               0.1s
 => => transferring dockerfile: 378B                                       0.0s
 => [internal] load .dockerignore                                          0.2s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for docker.io/library/node:lts-bullsey  1.9s
------
 > [internal] load metadata for docker.io/library/node:lts-bullseye:
------
failed to solve: executor failed running [/bin/sh -c /tmp/install_solidity.sh]:
exit code: 127
[70375 ms] Error: Command failed: docker-compose --project-name gif-sandbox_devcontainer -f d:\myprojekts\Etherisc8\gif-sandbox\.devcontainer\docker-compose.yaml -f c:\Users\User\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.build-1678009382974.yml build
[70376 ms]     at yF (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\spec-node\devContainersSpecCLI.js:1896:412)
[70376 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[70376 ms]     at async sie (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\spec-node\devContainersSpecCLI.js:1896:2381)
[70376 ms]     at async iie (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\spec-node\devContainersSpecCLI.js:1878:2396)
[70377 ms]     at async xie (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\spec-node\devContainersSpecCLI.js:1945:2798)
[70378 ms]     at async Wf (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\spec-node\devContainersSpecCLI.js:1945:3750)
[70378 ms]     at async noe (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\spec-node\devContainersSpecCLI.js:2069:17325)
[70378 ms]     at async roe (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\spec-node\devContainersSpecCLI.js:2069:17066)
[70413 ms] Exit code 1
[70422 ms] Command failed: C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\User\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-268c5468-4edc-454a-95fb-7dbdcc0ac8541678009308922 --workspace-folder d:\myprojekts\Etherisc8\gif-sandbox --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\myprojekts\Etherisc8\gif-sandbox --id-label devcontainer.config_file=d:\myprojekts\Etherisc8\gif-sandbox\.devcontainer\devcontainer.json --log-level debug --log-format json --config d:\myprojekts\Etherisc8\gif-sandbox\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[70423 ms] Exit code 1

**Comment by Fenum88** [comment]
maybe it has something to do with:

[35544 ms] Start: Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.282.0.js'
[35546 ms] 
[35547 ms] 
[35554 ms] Host server: /bin/sh: /root/.vscode-remote-containers/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node: not found
[35555 ms] userEnvProbe: loginInteractiveShell (default)
[35555 ms] userEnvProbe: not found in cache
[35557 ms] userEnvProbe shell: /bin/sh
[35643 ms] Error: stream ended with:0 but wanted:9
        at c (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:11:66217)
        at c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:11:66398
        at s (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:14:5371)
        at Socket.<anonymous> (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:14:5541)
        at Socket.emit (node:events:538:35)
        at endReadableNT (node:internal/streams/readable:1345:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Fenum88** [comment]
[remoteContainers-2023-03-05T09-51-27.706Z.log](https://github.com/etherisc/gif-sandbox/files/10891532/remoteContainers-2023-03-05T09-51-27.706Z.log)

uploaded the full log, so you can analyse it better
